### ISSUE TITLE
Help au téléchargement 

### ISSUE THREAD

**Issue by Fatoxe** [HiroshimaTeam/EffectStick#1]
Sa me demande une autorisation push pour télécharger

**Comment by HiroshimaTeam** [comment]
Bonjour, 

Le téléchargement ne requière pas d'autorisation. 
Veillez suivre les étapes du screen ! 

WillyDuGang 

![Screenshot_20210224_144230](https://user-images.githubusercontent.com/65712904/109009207-8f918d80-76ae-11eb-8cf4-d2a80c1affbc.jpg)
